services:

  _defaults:
    public: false
    autowire: true

  Lcobucci\JWT\Token:
    factory: ['@OxidEsales\GraphQL\Base\Framework\RequestReader', 'getAuthToken']

  OxidEsales\GraphQL\Base\Service\Authentication:
    class: OxidEsales\GraphQL\Base\Service\Authentication

  OxidEsales\GraphQL\Base\Service\Legacy:
    class: OxidEsales\GraphQL\Base\Service\Legacy

  OxidEsales\GraphQL\Base\Service\Authorization:
    class: OxidEsales\GraphQL\Base\Service\Authorization
    arguments:
        $permissionProviders: !tagged graphql_permission_provider

  OxidEsales\GraphQL\Base\Controller\:
    resource: 'src/Controller/'
    public: true

  OxidEsales\GraphQL\Base\Service\NamespaceMapper:
    class: OxidEsales\GraphQL\Base\Service\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Base\Framework\SchemaFactory:
    class: OxidEsales\GraphQL\Base\Framework\SchemaFactory
    arguments:
      $namespaceMappers: !tagged graphql_namespace_mapper
      $cache: '@oxidesales.graphqlbase.cache'

  OxidEsales\GraphQL\Base\Event\Subscriber\ModuleChangeSubscriber:
    class: OxidEsales\GraphQL\Base\Event\Subscriber\ModuleChangeSubscriber
    public: true
    arguments:
      $cache: '@oxidesales.graphqlbase.cache'
    tags:
      - {name: kernel.event_subscriber}

  oxidesales.graphqlbase.cacheadapter:
    class: Symfony\Component\Cache\Adapter\NullAdapter

  oxidesales.graphqlbase.cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      $pool: '@oxidesales.graphqlbase.cacheadapter'
