services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Base\Framework\ModuleSetup:
    class: OxidEsales\GraphQL\Base\Framework\ModuleSetup
    public: true

  OxidEsales\GraphQL\Base\Framework\GraphQLQueryHandler:
    class: OxidEsales\GraphQL\Base\Framework\GraphQLQueryHandler
    public: true

  OxidEsales\GraphQL\Base\Framework\ErrorCodeProvider:
    class: OxidEsales\GraphQL\Base\Framework\ErrorCodeProvider

  OxidEsales\GraphQL\Base\Framework\RequestReader:
    class: OxidEsales\GraphQL\Base\Framework\RequestReader

  OxidEsales\GraphQL\Base\Framework\ResponseWriter:
    class: OxidEsales\GraphQL\Base\Framework\ResponseWriter

  OxidEsales\GraphQL\Base\Service\KeyRegistry:
    class: OxidEsales\GraphQL\Base\Service\KeyRegistry
    public: true

  Lcobucci\JWT\Token:
    factory: ['@OxidEsales\GraphQL\Base\Framework\RequestReader', 'getAuthToken']

  OxidEsales\GraphQL\Base\Service\Authentication:
    class: OxidEsales\GraphQL\Base\Service\Authentication

  OxidEsales\GraphQL\Base\Service\Legacy:
    class: OxidEsales\GraphQL\Base\Service\Legacy

  OxidEsales\GraphQL\Base\Service\Authorization:
    class: OxidEsales\GraphQL\Base\Service\Authorization
    arguments:
        $permissionProviders: !tagged graphql_permission_provider

  OxidEsales\GraphQL\Base\Controller\:
    resource: '../../../../vendor/oxid-esales/graphql-base/src/Controller/'
    public: true

  OxidEsales\GraphQL\Base\Service\NamespaceMapper:
    class: OxidEsales\GraphQL\Base\Service\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Base\Framework\SchemaFactory:
    class: OxidEsales\GraphQL\Base\Framework\SchemaFactory
    arguments:
      $namespaceMappers: !tagged graphql_namespace_mapper
