services:
    
    OxidEsales\GraphQl\Framework\GraphQlQueryHandlerInterface:
        class: OxidEsales\GraphQl\Framework\GraphQlQueryHandler
        arguments:
            $logger: '@Psr\Log\LoggerInterface'
            $environmentService: '@OxidEsales\GraphQl\Service\EnvironmentServiceInterface'
            $keyRegistry: '@OxidEsales\GraphQl\Service\KeyRegistryInterface'
            $schemaFactory: '@OxidEsales\GraphQl\Framework\SchemaFactoryInterface'
            $errorCodeProvider: '@OxidEsales\GraphQl\Framework\ErrorCodeProviderInterface'
            $requestReader: '@OxidEsales\GraphQl\Framework\RequestReaderInterface'
            $responseWriter: '@OxidEsales\GraphQl\Framework\ResponseWriterInterface'
        public: true

    OxidEsales\GraphQl\Framework\RequestReaderInterface:
        class: OxidEsales\GraphQl\Framework\RequestReader
        public: false
        autowire: true

    OxidEsales\GraphQl\Framework\ResponseWriterInterface:
        class: OxidEsales\GraphQl\Framework\ResponseWriter
        public: false
        autowire: true

    OxidEsales\GraphQl\Framework\SchemaFactoryInterface:
        class: OxidEsales\GraphQl\Framework\SchemaFactory
        public: false
        autowire: true

    OxidEsales\GraphQl\Framework\GenericFieldResolverInterface:
        class: OxidEsales\GraphQl\Framework\GenericFieldResolver
        public: false
        autowire: true

    OxidEsales\GraphQl\Dao\UserDaoInterface:
        class: OxidEsales\GraphQl\Dao\UserDao
        public: false
        autowire: true

    OxidEsales\GraphQl\Service\KeyRegistryInterface:
        class: OxidEsales\GraphQl\Service\KeyRegistry
        public: false
        autowire: true

    OxidEsales\GraphQl\Service\EnvironmentServiceInterface:
        class: OxidEsales\GraphQl\Service\EnvironmentService
        public: false
        autowire: true

    OxidEsales\GraphQl\Service\AuthenticationServiceInterface:
        class: OxidEsales\GraphQl\Service\AuthenticationService
        public: true
        autowire: true

    OxidEsales\GraphQl\Service\UserServiceInterface:
        class: OxidEsales\GraphQl\Service\UserService
        public: false
        autowire: true

    OxidEsales\GraphQl\Service\PermissionsServiceInterface:
        class: OxidEsales\GraphQl\Service\PermissionsService
        public: false
        autowire: true

    OxidEsales\GraphQl\Service\LoginPermissionsProvider:
        class: OxidEsales\GraphQl\Service\PermissionsProvider
        calls:
            - ['addPermission', ['anonymous', 'mayreaddata']]
            - ['addPermission', ['customer', 'mayreaddata']]
            - ['addPermission', ['admin', 'mayreaddata']]
            - ['addPermission', ['shopadmin', 'mayreaddata']]
        tags:
            - {'name': 'graphql_permissions_provider'}
        public: false
        autowire: true

    OxidEsales\GraphQl\Service\UserPermissionsProvider:
        class: OxidEsales\GraphQl\Service\PermissionsProvider
        calls:
            - ['addPermission', ['anonymous', 'maycreatecustomer']]
            - ['addPermission', ['customer', 'mayupdateself']]
            - ['addPermission', ['customer', 'maygetself']]
            - ['addPermission', ['shopadmin', 'maycreateanyuser']]
            - ['addPermission', ['shopadmin', 'maygetshopuser']]
            - ['addPermission', ['admin', 'maycreateanyuser']]
            - ['addPermission', ['admin', 'maygetanyuser']]
            - ['addPermission', ['admin', 'maycreateuserforothershop']]
            - ['addPermission', ['admin', 'mayupdateanyuser']]
        tags:
            - {'name': 'graphql_permissions_provider'}
        public: false
        autowire: true

    OxidEsales\GraphQl\Type\Provider\LoginQueryProvider:
        class: OxidEsales\GraphQl\Type\Provider\LoginQueryProvider
        tags:
            - {'name': 'graphql_query_provider'}
        public: false
        autowire: true

    OxidEsales\GraphQl\Type\Provider\UserMutationProvider:
        class: OxidEsales\GraphQl\Type\Provider\UserMutationProvider
        tags:
            - {'name': 'graphql_mutation_provider'}
            - {'name': 'graphql_query_provider'}
        public: false
        autowire: true

    OxidEsales\GraphQl\Utility\LegacyWrapperInterface:
        class: OxidEsales\GraphQl\Utility\LegacyWrapper
        public: false
        autowire: true
